### ISSUE TITLE
[PROPOSED] Add default passthrough to prevent Chrome for iOS "unverified URL" errors

### ISSUE THREAD

**Issue by anulman** [samselikoff/ember-cli-mirage#552]
When configured for production, Mirage (via Pretender) intercepts Chrome for iOS' default URL verification, as noted [in this blog post](
http://blog.isleofcode.com/configuring-ember-cli-mirage-and-pretender-for-production/).

In discussion via Ember-Slack, @samselikoff agreed this solution would be nice to add as a default-but-configurable option in Mirage.

#### ToDo
- [x] add `defaultPassthroughs` array as config option to [config/environment.js#L22](https://github.com/samselikoff/ember-cli-mirage/blob/master/config/environment.js#L22) (defaults to `true`)
- [x] add `this.configureDefaultPassthroughs` function to [server.js#L97-L132](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L97-L132)
    - [x] add file-level `const defaultPassthroughUrls = [...]`
    - [x] for each `defaultPassthroughUrl`, `server.passthrough(foo)`
- [x] add tests to validate default passthroughs are configured per boolean state

#### Questions
- Should we restrict this config setting to production environments only?

> No; users can refine as necessary

- Is it ok to import Ember's `isBlank` fn, or should we default to a more manual `typeof` / `instanceof` approach?

> Use `lodash/lang/isEmpty` per @samselikoff's suggestion below

**Comment by samselikoff** [comment]
Thanks for kicking this off!

I actually think this is [constructor logic](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L97), rather than initializer. Users should be able to configure via `ENV['ember-cli-mirage']`, but those options already end up in the `options` hash passed to `Server`'s constructor. So let's do it there.

I think `defaultPassthroughs` should just be `true` or `false`... if users want to configure an array of passthroughs different from the default, I think they should just do it in `config.js`, like they can already. No reason to introduce another way of specifying passthrough URLs, especially because `passthrough` already takes a list of URLs. Does that sound right?

Agree w/you, this is just an `ENV` option so can be set in all environments.

As for empty check let's use

```
import _isEmpty from 'lodash/lang/isEmpty';
```

I prefer keep Mirage core as independent of Ember as possible, if we ever decide to move it into a separate lib.

**Comment by anulman** [comment]
Ha! That was the other place I was looking at; very glad I asked.

I agree with you re: using a bool; I was waffling with regards to bool vs. array myself, and opted for array in case other addon devs wanted to hook in. Unless you object, I'd prefer to call it `useDefaultPassthroughs`, if only because the name is a better indicator of boolean-ness.

Since this is happening in the constructor, I'm thinking of simply adding unit tests for `server.js` in both boolean states, and checking via [`this.pretender.checkPassthrough`](https://github.com/pretenderjs/pretender/blob/master/pretender.js#L289-L305). Unless you have a better idea, of course :)

Will update the above notes now, and will get something ready & shippable by EOW.

**Comment by samselikoff** [comment]
All sounds good. Thank you!
