### ISSUE TITLE
[Quest] Reimplement belongsTo and hasMany using the new storage engine

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#887]
These will no longer add foreign keys to other models, they need to only set up relationships for the model on which they are defined.

With #886 resolved I can now outline what needs to be done.
# TODO
## belongs to

- [x] basic
- [x] named
- [x] reflexive
- [x] named reflexive
- [x] one-way reflexive
- [x] one-to-one

## has many

- [x] basic
- [x] named
- [x] reflexive
- [x] named reflexive
- [x] one-way reflexive
- [x] many-to-many

## mixed

- [x] one-to-many
- [x] reflexive, one-to-many
- [x] polymorphic
- [ ] multiple with ambiguous implicit inverse

# Details

Current ORM tests are already complex, but I fear this is just the nature of an ORM. A child model with a belongsTo parent association can be in six states with respect to its parent:
- the child can be saved and the parent can be one of: undefined, new or saved
- the child can be new and the parent can be one of: undefined, new or saved

This is how things currently stand. With the new changes coming, we have additional complexity. The basic `belongsTo` case is now just one of several schema definitions. Here's the exhaustive list:

Given Post, Author models
## basic

author: belongsTo()
## named

writer: belongsTo('author')
## reflexive

post: belongsTo()
## named reflexive

childPost: belongsTo('post')
## implicit inverse

author: belongsTo()

(author)
posts: hasMany()
## explicit inverse

author: belongsTo('author', { inverse: 'redPosts' })

(author)
posts: hasMany('post', { inverse: 'author' })
drafts: hasMany('post')
## null inverse

author: belongsTo('author')
reviewer: belongsTo('author', { inverse: null })

(author)
posts: hasMany('post', { inverse: 'author' })
## multiple (conflict)

primaryAuthor: belongsTo('author')
secondaryAuthor: belongsTo('author')

(author)
posts: hasMany()

**Comment by samselikoff** [comment]
Let me know if you see anything missing on the belongsTo side. I'll probably do the basic cases first (one-way), and then do one-way hasMany, and then work on the inverses.
